import pichler

device = pichler.Pichler()

print('Ping response: %s' % device.Ping())
print('')

data = device.DatapointReadValues(0, 0, 128)

print('Current temperature: %.2f C' % (data[19] / 100.0))
print('')
print('Power consumption')
print('  Total            : %.1f W' % ((data[24] + data[25] + data[26]) / 10.0))
print('  Ventilation      : %.1f W' % (data[26] / 10.0))
print('  Heat pump        : %.1f W' % (data[25] / 10.0))
print('  Hot water        : %.1f W' % (data[24] / 10.0))
print('')
print('Energy consumption')
print('  Total            : %d kWh' % data[65])
print('  Ventilation      : %d kWh' % data[29])
print('  Heating          : %d kWh' % data[64])
print('  Cooling          : %d kWh' % data[27])
print('  Hot water        : %d kWh' % data[38])
print('')
print('Air flow')
print('  Level            : %d' % device.DatapointReadValue(41, 1))
print('  Supply           : %.2f m3/h' % (data[22] / 10.0))
print('  Extract          : %.2f m3/h' % (data[23] / 10.0))
print('')
print('Air temperature')
print('  Supply           : %.2f C' % (device.DatapointReadValue(1, 1) / 100.0))
print('  Extract          : %.2f C' % (device.DatapointReadValue(6, 1) / 100.0))
print('  Outdoor          : %.2f C' % (device.DatapointReadValue(2, 1) / 100.0))
print('  Exhaust          : %.2f C' % (device.DatapointReadValue(3, 1) / 100.0))
print('')
print('Hot water')
print('  Center           : %.2f C' % (device.DatapointReadValue(12, 1) / 100.0))
print('  Bottom           : %.2f C' % (device.DatapointReadValue(13, 1) / 100.0))
print('')
print('Various')
print('  Status bits      : %s' % hex(device.DatapointReadValue(152, 1) & 0xffff))
print('  CO2 level        : %d ppm' % device.DatapointReadValue(153, 1))
print('  Malfunction      : %d' % device.DatapointReadValue(34, 0))
print('  Filter change    : %d days' % (device.SetpointReadValue(18, 2) / 12))
print('  SCOP             : %.2f' % (data[44] / 100.0))
print('  HP COP           : %.2f' % (data[45] / 100.0))
print('  HP heating power : %d W' % (data[37]))
